### ISSUE TITLE
Define Codeowners and Maintainers for the new repository

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityByDesign#1]
**Problem description**

There are currently no Codeowners and Maintainers defined for this new repository.

**Expected action**

Collect the initial Codeowners and Maintainers within https://github.com/camaraproject/APIBacklog/issues/70 and create a PR to update /CODEOWNERS and /MAINTAINERS.md accordingly.

**Additional context**

**Comment by hdamker** [comment]
@benhepworth @patriciaserranog, see above.

**Comment by benhepworth** [comment]
got it - thanks @hdamker - have been traveling, but will put a PR in for owners and maintainers this week.
