### ISSUE TITLE
Describe the concept and propose an appropriate name for the work within the repository

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityByDesign#3]
**Problem description**

Within TSC meeting at 2024-09-05 the creation of the API Repository within the Sub Project of Connectivity Insights was approved with the following request to the project team. The background is that the term "QualityByDesign" and the concept behind it is much broader then a single API and might include APIs like connectivity-insights and quality-on-demand and how they are used in combination. It is open if the concept of QualityByDesign actually will need the definition of new APIs or will be more an overarching service achieved by already defined APIs with some modifications.

**Expected action**

The TSC proposed the following steps:

-  @benhepworth provides user story/ies, 
- (Project team) Discuss the concept & propose rename
- (TSC) Adjust the name

**Additional context**

Please cf. with the TSC minutes (https://lf-camaraproject.atlassian.net/wiki/x/5jDe), also regarding the further comments on the proposal.

**Comment by benhepworth** [comment]
Herbert,

I’ve been out of town this week at a conference. Will circle back to the QbD stuff next week.

-Ben
________________________________

**Comment by benhepworth** [comment]
Discussion started for name: https://github.com/camaraproject/QualityByDesign/discussions/8

**Comment by benhepworth** [comment]
hi @hdamker - see discussion https://github.com/camaraproject/QualityByDesign/discussions/8 - the name chosen is "Session Insights"

**Comment by benhepworth** [comment]
Link to meeting notes from last Connectivity Insights meeting where the new name was decided upon: https://lf-camaraproject.atlassian.net/wiki/x/mIDoAQ
