### ISSUE TITLE
Enable Discussions in QbD Repo

### ISSUE THREAD

**Issue by benhepworth** [camaraproject/QualityByDesign#6]
**Problem description**
Enable discussions in QbD Repo.

**Expected action**
Disscussions are allowed in QbD Repo.

**Additional context**
The Settings button doesn't show up for me so I can't enable discussions. Will you or someone who has access enable them for the QualityByDesign Repo, @hdamker ?

**Comment by hdamker** [comment]
@benhepworth Sure, done.
